#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/private/tmp/homebrew-autoconf-2.68b-whdT/autoconf-2.68b/tests'
exec ${CONFIG_SHELL-/bin/sh} "/private/tmp/homebrew-autoconf-2.68b-whdT/autoconf-2.68b/tests/./testsuite" -v -d  407 ${1+"$@"}
exit 1
